CREATE DATABASE LoginNCapasBD
GO

--PONER EN USO

USE LoginNCapasBD
GO

--TABLA

CREATE TABLE Users(
ID INT IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(30),
Lastname NVARCHAR(30),
Username NVARCHAR(30),
Pass NVARCHAR(30)
);

--VER TABLA

SELECT * FROM Users
GO

--PROCEDIMIENTO ALMACENADO

CREATE PROC SP_CreateUser
@Name NVARCHAR(30),
@Lastname NVARCHAR(30),
@Username NVARCHAR(30),
@Pass NVARCHAR(30)
AS
INSERT INTO Users VALUES(@Name, @Lastname, @Username, @Pass)
GO